# Generated by Django 5.0.6 on 2024-06-24 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('organizacion', models.CharField(max_length=100)),
                ('encargado', models.CharField(max_length=100)),
                ('firmas', models.IntegerField(default=0)),
                ('fecha_finalizacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('voto', models.BooleanField()),
                ('voto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votos.voto')),
            ],
        ),
    ]
