# Generated by Django 5.0.6 on 2024-06-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='evento',
            field=models.CharField(default='Evento General', max_length=100),
            preserve_default=False,
        ),
    ]
