# Generated by Django 5.0.6 on 2024-06-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_voto_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
